import './globals.scss'
import styles from './page.module.scss'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import cl from 'classnames'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className='container'>{children}</body>
    </html>
  )
}
